"""empty message

Revision ID: 05cdfba984f0
Revises: de497dfdfe33
Create Date: 2022-01-20 00:41:32.894624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cdfba984f0'
down_revision = 'de497dfdfe33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('cardlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardlist_id'], ['card_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information')
    # ### end Alembic commands ###
