"""empty message

Revision ID: 1194e8961bd9
Revises: bc969f7d2785
Create Date: 2022-01-16 15:05:55.781484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1194e8961bd9'
down_revision = 'bc969f7d2785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_list', 'information',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_list', 'information',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
