"""empty message

Revision ID: 1e8e1e9b8628
Revises: ac387695d9be
Create Date: 2022-01-20 11:03:24.779973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8e1e9b8628'
down_revision = 'ac387695d9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cardabout', 'title3',
               existing_type=sa.BLOB(),
               type_=sa.String(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cardabout', 'title3',
               existing_type=sa.String(length=2048),
               type_=sa.BLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
