"""empty message

Revision ID: 2bbeefb5909b
Revises: b4c63b8ec859
Create Date: 2022-01-20 10:41:49.717817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bbeefb5909b'
down_revision = 'b4c63b8ec859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cardabout', 'title1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cardabout', 'text1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cardabout', 'title2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cardabout', 'list1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cardabout', 'list2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cardabout', 'list3',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cardabout', 'list4',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cardabout', 'title3',
               existing_type=sa.BLOB(),
               nullable=False)
    op.alter_column('cardabout', 'title4',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cardabout', 'title4',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cardabout', 'title3',
               existing_type=sa.BLOB(),
               nullable=True)
    op.alter_column('cardabout', 'list4',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cardabout', 'list3',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cardabout', 'list2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cardabout', 'list1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cardabout', 'title2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cardabout', 'text1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cardabout', 'title1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
