"""empty message

Revision ID: 6138dcc7ee9f
Revises: fc72f74c80a0
Create Date: 2022-01-20 10:21:03.380440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6138dcc7ee9f'
down_revision = 'fc72f74c80a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardabout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title1', sa.String(length=255), nullable=True),
    sa.Column('text1', sa.String(length=255), nullable=True),
    sa.Column('title2', sa.String(length=255), nullable=True),
    sa.Column('list1', sa.String(length=255), nullable=True),
    sa.Column('list2', sa.String(length=255), nullable=True),
    sa.Column('list3', sa.String(length=255), nullable=True),
    sa.Column('list4', sa.String(length=255), nullable=True),
    sa.Column('title3', sa.String(length=255), nullable=True),
    sa.Column('title4', sa.String(length=255), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cardabout')
    # ### end Alembic commands ###
