"""empty message

Revision ID: ac387695d9be
Revises: 2bbeefb5909b
Create Date: 2022-01-20 10:54:54.774914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac387695d9be'
down_revision = '2bbeefb5909b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardabout', 'list2')
    op.drop_column('cardabout', 'list3')
    op.drop_column('cardabout', 'list4')
    op.drop_column('cardabout', 'list1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardabout', sa.Column('list1', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('cardabout', sa.Column('list4', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('cardabout', sa.Column('list3', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('cardabout', sa.Column('list2', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
