"""empty message

Revision ID: f487cb2d4b2b
Revises: e1b9a944f0fa
Create Date: 2022-01-19 23:58:16.171613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f487cb2d4b2b'
down_revision = 'e1b9a944f0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('cardlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardlist_id'], ['card_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information')
    # ### end Alembic commands ###
