"""empty message

Revision ID: fc72f74c80a0
Revises: 30b8fd1125c7
Create Date: 2022-01-20 07:43:37.044826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc72f74c80a0'
down_revision = '30b8fd1125c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('money', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('surname', sa.String(length=500), nullable=True),
    sa.Column('prefiks', sa.String(length=30), nullable=True),
    sa.Column('phonenumber', sa.String(length=30), nullable=True),
    sa.Column('codetext', sa.String(length=255), nullable=True),
    sa.Column('filial', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cardform')
    # ### end Alembic commands ###
